# Generated by Django 5.2.4 on 2025-08-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='activity',
            name='exercise_type',
            field=models.CharField(choices=[('Push Ups', 'Push Ups'), ('Sit Ups', 'Sit Ups'), ('Squats', 'Squats'), ('Lunges', 'Lunges'), ('Plank', 'Plank'), ('Burpees', 'Burpees'), ('Jumping Jacks', 'Jumping Jacks'), ('Pull Ups', 'Pull Ups'), ('Bench Press', 'Bench Press'), ('Deadlift', 'Deadlift'), ('Other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
