# Generated by Django 5.2.4 on 2025-08-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='exercise_type',
            new_name='activity_type',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='calories_burned',
            new_name='calories',
        ),
    ]
